<a href="https://colab.research.google.com/github/Anushka6602/SD_Anushka_0069/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]

In [ ]:
type(l)

list

In [ ]:
ar=np.array(l)

In [ ]:
ar

array([1, 2, 3, 4])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
a=[2,3,4]

In [ ]:
np.asanyarray

<function numpy.asanyarray>

In [ ]:
b=np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])